{
 "title": "cluster_tab",
 "description": "Clustering solution showing single machine stats",
 "tags": [
  "prometheus",
  "lightbits"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "Cluster_name", "query": { "query": "label_values(up,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   { "name": "Prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 14, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:cluster:number_of_volumes{job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (instance:volume:volume_state_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum (instance:volume:volume_state_read_only{job=\"$job\"})",
     "legendFormat": "Read only"
    }
   ]
  },
  {
   "title": "Lightbits version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lightbox_clustering_cluster_info{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{cluster_lightos_version}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lightbox_clustering_node_state_active{job=\"$job\", instance=\"$instance\"}) + sum(lightbox_clustering_node_state_inactive{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "tbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:cluster:effective_physical_storage{job=\"$job\"}/1024^4"
    }
   ]
  },
  {
   "title": "Info alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=\"$job\", severity=\"info\"})"
    }
   ]
  },
  {
   "title": "Warning alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=\"$job\", severity=\"warning\"})"
    }
   ]
  },
  {
   "title": "Critical alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=\"$job\", severity=\"critical\"})"
    }
   ]
  },
  {
   "title": "Cluster name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lightbox_clustering_cluster_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Alerts history",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "ALERTS{job=\"$job\"}+0"
    }
   ]
  },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(instance:cluster:health_ok{job=\"$job\"}*10) + (instance:cluster:health_error{job=\"$job\"}*1000) + (instance:cluster:health_warning{job=\"$job\"}*100)"
    }
   ]
  },
  {
   "title": "Used capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "tbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:cluster:physical_used_storage{job=\"$job\"}/1024^4"
    }
   ]
  },
  {
   "title": "Connected hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(lightbox_clustering_num_connected_hosts{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1/instance:cluster:compression_ratio{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Provisioned capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "tbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:cluster:logical_storage{job=\"$job\"}/1024^4"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*((sum(irate(lightbox_fe_nr_read_requests_0_1K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_1K_8K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_8K_32K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_32K_128K{job=\"$job\"}[1m])))  / (sum(irate(lightbox_fe_nr_read_requests_0_1K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_1K_8K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_8K_32K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_32K_128K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_0_1K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_1K_8K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_8K_32K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_32K_128K{job=\"$job\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Read bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:cluster:read_throughput{job=\"$job\"}",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:cluster:read_iops{job=\"$job\"}",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*((sum(irate(lightbox_fe_nr_write_requests_0_1K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_1K_8K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_8K_32K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_32K_128K{job=\"$job\"}[1m])))/ (sum(irate(lightbox_fe_nr_read_requests_0_1K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_1K_8K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_8K_32K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_read_requests_32K_128K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_0_1K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_1K_8K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_8K_32K{job=\"$job\"}[1m])) + sum(irate(lightbox_fe_nr_write_requests_32K_128K{job=\"$job\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Nodes state",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lightbox_clustering_node_state_active{job=\"$job\", instance=\"$instance\"}==1) OR on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(lightbox_clustering_node_state_inactive{job=\"$job\", instance=\"$instance\"} == 1) OR on() vector(0)",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Write bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:cluster:write_throughput{job=\"$job\"}",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:cluster:write_iops{job=\"$job\"}",
     "legendFormat": "cluster"
    }
   ]
  }
 ]
}