{
 "title": "nodes_tab",
 "description": "Clustering solution showing single machine stats",
 "tags": [
  "prometheus",
  "lightbits"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node_id",
    "label": "Node_id",
    "query": {
     "query": "label_values(lightbox_clustering_node_effective_physical_storage{job=\"$job\"}, node_id)"
    }
   },
   { "name": "Prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "${node_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node_id" },
  {
   "title": "Node name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node:effective_physical_storage{node_id=\"$node_id\"}",
     "legendFormat": "{{cluster_lightos_version}}"
    }
   ]
  },
  {
   "title": "Read bandwidth",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node:read_throughput{node_id=\"$node_id\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Write bandwidth",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node:write_throughput{node_id=\"$node_id\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "tbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(instance:node:effective_physical_storage{node_id=\"$node_id\"})/1024^4"
    }
   ]
  },
  {
   "title": "Lightbits version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lightbox_clustering_node_info{job=\"$job\", node_id=\"$node_id\"}",
     "legendFormat": "{{node_lightos_version}}"
    }
   ]
  },
  {
   "title": "Used capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "tbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node:physical_used_storage{node_id=\"$node_id\"}/1024^4"
    }
   ]
  },
  {
   "title": "Node health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(lightbox_clustering_node_state_active{node_id=\"$node_id\"}*10) + max(lightbox_clustering_node_state_inactive{node_id=\"$node_id\"}*1000) + max(lightbox_clustering_node_local_rebuild_progress{node_id=\"$node_id\"} OR on() vector(0))*100"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:node:read_iops{node_id=\"$node_id\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:node:write_iops{node_id=\"$node_id\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "% Occupied Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(instance:node:physical_used_storage{node_id=\"$node_id\"}* 100) / ((instance:node:effective_physical_storage{node_id=\"$node_id\"}))"
    }
   ]
  }
 ]
}