{
 "title": "Lightbits Server Performance Tab",
 "description": "View Lightbits Server Performance",
 "tags": [
  "prometheus",
  "lightbits"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "allocation_descriptor",
    "query": {
     "query": "query_result(max_over_time(up{instance=~\".+:$exporter_port\"}[$__range])==1)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values({$allocation_descriptor}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({$allocation_descriptor}, instance)"
    }
   },
   { "name": "Prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "exporter_port", "query": "${VAR_EXPORTER_PORT}" }
  ]
 },
 "panels": [
  {
   "title": "SSD Smart Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available Spare",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "lightbox_smart_available_spare_percent{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Controller Busy Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "lightbox_smart_controller_busy_time{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Critical Warning",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(lightbox_smart_critical_warning{$allocation_descriptor})",
       "legendFormat": "Total"
      },
      {
       "expr": "lightbox_smart_critical_warning{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Media And Data Integrity Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(lightbox_smart_media_and_data_integrity_errors{$allocation_descriptor})",
       "legendFormat": "Total"
      },
      {
       "expr": "lightbox_smart_media_and_data_integrity_errors{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Power Cycles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lightbox_smart_power_cycles{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Error Log Entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(lightbox_smart_error_information_log_entries{$allocation_descriptor})",
       "legendFormat": "Total"
      },
      {
       "expr": "lightbox_smart_error_information_log_entries{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Power On Hours",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "h" }
     ],
     "targets": [
      {
       "expr": "lightbox_smart_power_on_hours{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "lightbox_smart_temperature_celsius{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Unsafe Shutdowns",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lightbox_smart_unsafe_shutdowns{$allocation_descriptor}",
       "legendFormat": "{{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RX Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node:receive_bytes_total{$allocation_descriptor}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "instance:node:receive_packets_total{$allocation_descriptor}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RX Packets Dropped Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node:receive_drop_total{$allocation_descriptor})",
     "legendFormat": "Total"
    },
    {
     "expr": "instance:node:receive_drop_total{$allocation_descriptor}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "TX Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node:transmit_bytes_total{$allocation_descriptor}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "instance:node:transmit_packets_total{$allocation_descriptor}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RX Packets Error Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node:receive_errs_total{$allocation_descriptor})",
     "legendFormat": "Total"
    },
    {
     "expr": "instance:node:receive_errs_total{$allocation_descriptor}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "GFTL General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Powerup Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 10 * lightbox_be_num_processed_storage_scheme_units{$allocation_descriptor} / lightbox_be_total_units{$allocation_descriptor}) + (90 * lightbox_be_num_completed_units{$allocation_descriptor} / lightbox_be_num_units_to_recover{$allocation_descriptor})",
     "legendFormat": "Abrupt Powerup Percentage node {{node_id}}"
    }
   ]
  },
  {
   "title": "Local Rebuild",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "lightbox_clustering_node_local_rebuild_progress{$allocation_descriptor}",
     "legendFormat": "Local Rebuild node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Write Amplification",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node:write_amplification{$allocation_descriptor}",
     "legendFormat": "Write Amplification node: {{node_id}}"
    }
   ]
  },
  {
   "title": "GFTL Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read Congestion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance, node_id) (lightbox_be_num_blkdev_threshold_reached{$allocation_descriptor})) / (sum by (instance, node_id) (lightbox_be_inflight_4k_requests_irate{$allocation_descriptor}) + sum by (instance, node_id) (lightbox_be_num_blkdev_threshold_reached{$allocation_descriptor}))",
     "legendFormat": "Read Congestion node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance,job,node_id) (lightbox_be_effective_write_unit_size{$allocation_descriptor})) * (avg by (instance,job,node_id) (rate(lightbox_be_write_unit_duration_count{$allocation_descriptor}[1m])))",
     "legendFormat": "Total (GC+User) Bandwidth node: {{node_id}}"
    },
    {
     "expr": "(avg by (instance,job,node_id) (lightbox_be_effective_write_unit_size{$allocation_descriptor})) * (avg by (instance,job,node_id) (rate(lightbox_be_num_of_gc_units{$allocation_descriptor}[1m])))",
     "legendFormat": "GC Bandwidth node: {{node_id}}"
    }
   ]
  },
  {
   "title": "SSD Read Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(delta(lightbox_be_read_storage_duration_count{$allocation_descriptor}[2m]) * 4096) / 120 ",
     "legendFormat": "Read Bandwidth node: {{node_id}}"
    }
   ]
  },
  {
   "title": "SSD 4K Read latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " (avg by (instance, node_id) (delta(lightbox_be_read_storage_duration_sum{$allocation_descriptor}[2m]))/ avg by (instance, node_id) (delta(lightbox_be_read_storage_duration_count {$allocation_descriptor} [2m])))/  scalar(lightbox_cpu_frequency_hertz{$allocation_descriptor})",
     "legendFormat": "Read Latency node: {{node_id}}"
    }
   ]
  },
  {
   "title": "SSD write unit latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance, node_id) (delta(lightbox_be_write_unit_duration_sum{$allocation_descriptor}[2m])) / avg by (instance, node_id) (delta(lightbox_be_write_unit_duration_count{$allocation_descriptor} [2m])))/ scalar(lightbox_cpu_frequency_hertz{$allocation_descriptor})",
     "legendFormat": "Write Latency node: {{node_id}}"
    }
   ]
  },
  {
   "title": "FE General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "instance:node:current_load_avg{instance=\"$instance\"}",
     "legendFormat": "Avg CPU Load node: {{node_id}}"
    },
    {
     "expr": "instance:node:current_load_min{instance=\"$instance\"}",
     "legendFormat": "Min CPU Load node: {{node_id}}"
    },
    {
     "expr": "instance:node:current_load_max{instance=\"$instance\"}",
     "legendFormat": "Max CPU Load node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:node:memory_cross_cpu_frees{instance=\"$instance\"}",
     "legendFormat": "Cross CPU Memory Frees node: {{node_id}}"
    },
    {
     "expr": "instance:node:memory_large_allocations{instance=\"$instance\"}",
     "legendFormat": "Large Memory Allocations node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Memory Congestion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node:memory_allocated_memory{instance=\"$instance\"} / instance:node:memory_total_memory{instance=\"$instance\"}",
     "legendFormat": "Memory Congestion {{node_id}}"
    }
   ]
  },
  {
   "title": "FE General Write Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write IOPS ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:node:write_iops{instance=\"$instance\"}",
     "legendFormat": "Total node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "instance:node:nr_write_request_duration_0_1K{instance=\"$instance\"}",
     "legendFormat": "0-1K node: {{node_id}}"
    },
    {
     "expr": "instance:node:nr_write_request_duration_1K_8K{instance=\"$instance\"}",
     "legendFormat": "1K-8K node: {{node_id}}"
    },
    {
     "expr": "instance:node:nr_write_request_duration_8K_32K{instance=\"$instance\"}",
     "legendFormat": "8K-32K node: {{node_id}}"
    },
    {
     "expr": "instance:node:nr_write_request_duration_32K_128K{instance=\"$instance\"}",
     "legendFormat": "32K-128K node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Write Bandwith",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node:write_throughput{instance=\"$instance\"}",
     "legendFormat": "Total node: {{node_id}}"
    }
   ]
  },
  {
   "title": "FE General Read Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:node:read_iops{instance=\"$instance\"}",
     "legendFormat": "Total node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "instance:node:read_throughput", "legendFormat": "Total node: {{node_id}}" }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "instance:node:nr_read_request_duration_0_1K{instance=\"$instance\"}",
     "legendFormat": "0-1K node: {{node_id}}"
    },
    {
     "expr": "instance:node:nr_read_request_duration_1K_8K{instance=\"$instance\"}",
     "legendFormat": "1K-8K node: {{node_id}}"
    },
    {
     "expr": "instance:node:nr_read_request_duration_8K_32K{instance=\"$instance\"}",
     "legendFormat": "8K-32K node: {{node_id}}"
    },
    {
     "expr": "instance:node:nr_read_request_duration_32K_128K{instance=\"$instance\"}",
     "legendFormat": "32K-128K node: {{node_id}}"
    }
   ]
  }
 ]
}