{
 "title": "Lightbits Volumes Performance Tab",
 "description": "Lightbits Volumes Performance",
 "tags": [
  "prometheus",
  "lightbits"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "allocation_descriptor",
    "query": {
     "query": "query_result(max_over_time(up{instance=~\".+:$exporter_port\"}[$__range])==1)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values({$allocation_descriptor}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({$allocation_descriptor}, instance)"
    }
   },
   {
    "name": "volume_name",
    "query": {
     "query": "label_values({$allocation_descriptor}, volume_name)"
    }
   },
   { "name": "Prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "exporter_port", "query": "8090" }
  ]
 },
 "panels": [
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "instance:volume:logical_used_storage{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}})"
    }
   ]
  },
  {
   "title": "FE Volume Read Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:volume:read_iops_per_volume{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}})"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "instance:volume:read_throughput_per_volume{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}})"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "instance:volume:volume_read_request_duration_0K_1K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (0-1K)"
    },
    {
     "expr": "instance:volume:volume_read_request_duration_1K_8K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (1K-8K)"
    },
    {
     "expr": "instance:volume:volume_read_request_duration_8K_32K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (8K-32K)"
    },
    {
     "expr": "instance:volume:volume_read_request_duration_32K_128K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (32K-128K)"
    }
   ]
  },
  {
   "title": "FE Volume Write Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "instance:volume:write_iops_per_volume{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}})"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "instance:volume:write_throughput_per_volume{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}})"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "instance:volume:volume_write_request_duration_0K_1K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (0-1K)"
    },
    {
     "expr": "instance:volume:volume_write_request_duration_1K_8K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (1K-8K):"
    },
    {
     "expr": "instance:volume:volume_write_request_duration_8K_32K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (8K-32K)"
    },
    {
     "expr": "instance:volume:volume_write_request_duration_32K_128K{job=\"$job\", volume_name=~\"$volume_name\"}",
     "legendFormat": "{{volume_name}} ({{project_name}}): (32K-128K)"
    }
   ]
  }
 ]
}